### Medicine Tests
GET http://localhost:7007/api/medicineTracker/

###

### Create medicine
POST http://localhost:7007/api/medicineTracker/medicines
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJcIk1hcmlhbSBFbG1pclwiIiwic3ViIjoibWFyaWFtIiwiZXhwIjoxNzYxMTU2NDE3LCJyb2xlcyI6IlVTRVIiLCJ1c2VybmFtZSI6Im1hcmlhbSJ9.xT8Zud86AZ0QapsIfTYMh01y5oKkCYKJ0kg2ysJGazo

{
  "name": "Panodil",
  "type": "painKiller",
  "symptomDescription": "smerter",
  "user": {"username": "mariam"}
}

###

### Get all medicines
GET http://{{url}}/api/medicineTracker/medicines
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJcIk1hcmlhbSBFbG1pclwiIiwic3ViIjoibWFyaWFtIiwiZXhwIjoxNzYxMTU2NDE3LCJyb2xlcyI6IlVTRVIiLCJ1c2VybmFtZSI6Im1hcmlhbSJ9.xT8Zud86AZ0QapsIfTYMh01y5oKkCYKJ0kg2ysJGazo

###

### Get medicine by id
GET http://localhost:7007/api/medicineTracker/medicines/1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJcIk1hcmlhbSBFbG1pclwiIiwic3ViIjoibWFyaWFtIiwiZXhwIjoxNzYxMTU2NDE3LCJyb2xlcyI6IlVTRVIiLCJ1c2VybmFtZSI6Im1hcmlhbSJ9.xT8Zud86AZ0QapsIfTYMh01y5oKkCYKJ0kg2ysJGazo

###

### delete medicine by id
DELETE http://localhost:7007/api/medicineTracker/medicines/1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJcIk1hcmlhbSBFbG1pclwiIiwic3ViIjoibWFyaWFtIiwiZXhwIjoxNzYxMTU2NDE3LCJyb2xlcyI6IlVTRVIiLCJ1c2VybmFtZSI6Im1hcmlhbSJ9.xT8Zud86AZ0QapsIfTYMh01y5oKkCYKJ0kg2ysJGazo
###

### delete medicine by id
GET http://localhost:7007/api/medicineTracker/medicines/1
Authorization: BearereyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJcIk1hcmlhbSBFbG1pclwiIiwic3ViIjoibWFyaWFtIiwiZXhwIjoxNzYxMTU2NDE3LCJyb2xlcyI6IlVTRVIiLCJ1c2VybmFtZSI6Im1hcmlhbSJ9.xT8Zud86AZ0QapsIfTYMh01y5oKkCYKJ0kg2ysJGazo

###

### Update medicine by ID
PUT http://localhost:7007/api/medicineTracker/medicines/1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJcIk1hcmlhbSBFbG1pclwiIiwic3ViIjoibWFyaWFtIiwiZXhwIjoxNzYxMTU2NDE3LCJyb2xlcyI6IlVTRVIiLCJ1c2VybmFtZSI6Im1hcmlhbSJ9.xT8Zud86AZ0QapsIfTYMh01y5oKkCYKJ0kg2ysJGazo

{
  "name": "Sertralin test",
  "type": "Antidepressant",
  "symptomDescription": "Behandling af angst og depression"
}

###

# =========================
### MedicineLog Tests

### Create medicineLog
POST http://localhost:7007/api/medicineTracker/medicineLog
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJcIk1hcmlhbSBFbG1pclwiIiwic3ViIjoibWFyaWFtIiwiZXhwIjoxNzYxMTU2NDE3LCJyb2xlcyI6IlVTRVIiLCJ1c2VybmFtZSI6Im1hcmlhbSJ9.xT8Zud86AZ0QapsIfTYMh01y5oKkCYKJ0kg2ysJGazo

{
  "dose": 25.0,
  "takenAt": "2025-10-21T11:30:00",
  "username": "mariam",
  "medicineName": "Sertralin"
}

###

### Get all medicineLogs
GET http://localhost:7007/api/medicineTracker/medicineLog
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJcIk1hcmlhbSBFbG1pclwiIiwic3ViIjoibWFyaWFtIiwiZXhwIjoxNzYxMTU2NDE3LCJyb2xlcyI6IlVTRVIiLCJ1c2VybmFtZSI6Im1hcmlhbSJ9.xT8Zud86AZ0QapsIfTYMh01y5oKkCYKJ0kg2ysJGazo

###

### Get medicineLog by id
GET http://localhost:7007/api/medicineTracker/medicineLog/1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJcIk1hcmlhbSBFbG1pclwiIiwic3ViIjoibWFyaWFtIiwiZXhwIjoxNzYxMTU2NDE3LCJyb2xlcyI6IlVTRVIiLCJ1c2VybmFtZSI6Im1hcmlhbSJ9.xT8Zud86AZ0QapsIfTYMh01y5oKkCYKJ0kg2ysJGazo

###

### delete medicineLog by id
DELETE http://localhost:7007/api/medicineTracker/medicineLog/1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJcIk1hcmlhbSBFbG1pclwiIiwic3ViIjoibWFyaWFtIiwiZXhwIjoxNzYxMTU2NDE3LCJyb2xlcyI6IlVTRVIiLCJ1c2VybmFtZSI6Im1hcmlhbSJ9.xT8Zud86AZ0QapsIfTYMh01y5oKkCYKJ0kg2ysJGazo

###

### delete medicineLog by id
GET http://localhost:7007/api/medicineTracker/medicineLog/1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJcIk1hcmlhbSBFbG1pclwiIiwic3ViIjoibWFyaWFtIiwiZXhwIjoxNzYxMTU2NDE3LCJyb2xlcyI6IlVTRVIiLCJ1c2VybmFtZSI6Im1hcmlhbSJ9.xT8Zud86AZ0QapsIfTYMh01y5oKkCYKJ0kg2ysJGazo


###

### Update medicineLog by ID
PUT http://localhost:7007/api/medicineTracker/medicineLog/1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJcIk1hcmlhbSBFbG1pclwiIiwic3ViIjoibWFyaWFtIiwiZXhwIjoxNzYxMTU2NDE3LCJyb2xlcyI6IlVTRVIiLCJ1c2VybmFtZSI6Im1hcmlhbSJ9.xT8Zud86AZ0QapsIfTYMh01y5oKkCYKJ0kg2ysJGazo


{
  "dose": 30.0,
  "takenAt": "2025-10-21T12:00:00"
}

###

# =========================
### User Tests

### Security
POST http://{{url}}/api/medicineTracker/auth/login
Content-Type: application/json

{
  "username": "mariam",
  "password": "1234"
}


###
GET http://{{url}}/api/medicineTracker/protected/user_demo
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJcIk1hcmlhbSBFbG1pclwiIiwic3ViIjoibWFyaWFtIiwiZXhwIjoxNzYxMTU2NDE3LCJyb2xlcyI6IlVTRVIiLCJ1c2VybmFtZSI6Im1hcmlhbSJ9.xT8Zud86AZ0QapsIfTYMh01y5oKkCYKJ0kg2ysJGazo

### registere
POST http://{{url}}/api/medicineTracker/auth/register
Content-Type: application/json

{
  "username": "test",
  "password": "1234"
}

###

### logger ind med den registeret bruger
POST http://localhost:7007/api/medicineTracker/auth/login
Content-Type: application/json

{
  "username": "test",
  "password": "1234"
}


###

### tjekker om det valid
GET http://{{url}}/api/medicineTracker/protected/user_demo
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJcIk1hcmlhbSBFbG1pclwiIiwic3ViIjoibWFyaWFtIiwiZXhwIjoxNzYxMTU2NDE3LCJyb2xlcyI6IlVTRVIiLCJ1c2VybmFtZSI6Im1hcmlhbSJ9.xT8Zud86AZ0QapsIfTYMh01y5oKkCYKJ0kg2ysJGazo


###

### A simple get request to the test endpoint. No need for login
GET {{url}}/api/medicineTracker/auth/test/