### Medicine Tests
GET http://localhost:7007/api/medicineTracker/

###

### Create medicine
POST http://localhost:7007/api/medicineTracker/medicines
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJcIk1hcmlhbSBFbG1pclwiIiwic3ViIjoibWFyaWFtIiwiZXhwIjoxNzYxMDY3NjI2LCJyb2xlcyI6IlVTRVIiLCJ1c2VybmFtZSI6Im1hcmlhbSJ9.u1ppEigCRzEi-rKQDA9oEoI7lvmhf7B_2KVZFXdL5WQ

{
  "name": "Panodil",
  "type": "painKiller",
  "symptomDescription": "smerter",
  "user": {"username": "mariam"}
}

###

### Get all medicines
GET http://{{url}}/api/medicineTracker/medicines
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJcIk1hcmlhbSBFbG1pclwiIiwic3ViIjoibWFyaWFtIiwiZXhwIjoxNzYxMDY3NjI2LCJyb2xlcyI6IlVTRVIiLCJ1c2VybmFtZSI6Im1hcmlhbSJ9.u1ppEigCRzEi-rKQDA9oEoI7lvmhf7B_2KVZFXdL5WQ

###

### Get medicine by id
GET http://localhost:7007/api/medicineTracker/medicines/1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJcIk1hcmlhbSBFbG1pclwiIiwic3ViIjoibWFyaWFtIiwiZXhwIjoxNzYxMDY3NjI2LCJyb2xlcyI6IlVTRVIiLCJ1c2VybmFtZSI6Im1hcmlhbSJ9.u1ppEigCRzEi-rKQDA9oEoI7lvmhf7B_2KVZFXdL5WQ

###

### delete medicine by id
DELETE http://localhost:7007/api/medicineTracker/medicines/1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJcIk1hcmlhbSBFbG1pclwiIiwic3ViIjoibWFyaWFtIiwiZXhwIjoxNzYxMDY4NTI5LCJyb2xlcyI6IlVTRVIiLCJ1c2VybmFtZSI6Im1hcmlhbSJ9.ZDzovItUpBZn25yHM6XHWTAO0T5bPvzkYc6VcWJG8Kg
###

### delete medicine by id
GET http://localhost:7007/api/medicineTracker/medicines/1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJcIk1hcmlhbSBFbG1pclwiIiwic3ViIjoibWFyaWFtIiwiZXhwIjoxNzYxMDY4NTI5LCJyb2xlcyI6IlVTRVIiLCJ1c2VybmFtZSI6Im1hcmlhbSJ9.ZDzovItUpBZn25yHM6XHWTAO0T5bPvzkYc6VcWJG8Kg

###

### Update medicine by ID
PUT http://localhost:7007/api/medicineTracker/medicines/1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJcIk1hcmlhbSBFbG1pclwiIiwic3ViIjoibWFyaWFtIiwiZXhwIjoxNzYxMDY4NTI5LCJyb2xlcyI6IlVTRVIiLCJ1c2VybmFtZSI6Im1hcmlhbSJ9.ZDzovItUpBZn25yHM6XHWTAO0T5bPvzkYc6VcWJG8Kg

{
  "name": "Sertralin test",
  "type": "Antidepressant",
  "symptomDescription": "Behandling af angst og depression"
}

###

# =========================
### MedicineLog Tests

### Create medicineLog
POST http://localhost:7007/api/medicineTracker/medicineLog
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJcIk1hcmlhbSBFbG1pclwiIiwic3ViIjoibWFyaWFtIiwiZXhwIjoxNzYxMDY4NTI5LCJyb2xlcyI6IlVTRVIiLCJ1c2VybmFtZSI6Im1hcmlhbSJ9.ZDzovItUpBZn25yHM6XHWTAO0T5bPvzkYc6VcWJG8Kg

{
  "dose": 25.0,
  "takenAt": "2025-10-21T11:30:00",
  "username": "mariam",
  "medicineName": "Sertralin"
}

###

### Get all medicineLogs
GET http://localhost:7007/api/medicineTracker/medicineLog
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJcIk1hcmlhbSBFbG1pclwiIiwic3ViIjoibWFyaWFtIiwiZXhwIjoxNzYxMDY4NTI5LCJyb2xlcyI6IlVTRVIiLCJ1c2VybmFtZSI6Im1hcmlhbSJ9.ZDzovItUpBZn25yHM6XHWTAO0T5bPvzkYc6VcWJG8Kg

###

### Get medicineLog by id
GET http://localhost:7007/api/medicineTracker/medicineLog/1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJcIk1hcmlhbSBFbG1pclwiIiwic3ViIjoibWFyaWFtIiwiZXhwIjoxNzYxMDY4NTI5LCJyb2xlcyI6IlVTRVIiLCJ1c2VybmFtZSI6Im1hcmlhbSJ9.ZDzovItUpBZn25yHM6XHWTAO0T5bPvzkYc6VcWJG8Kg

###

### delete medicineLog by id
DELETE http://localhost:7007/api/medicineTracker/medicineLog/1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJcIk1hcmlhbSBFbG1pclwiIiwic3ViIjoibWFyaWFtIiwiZXhwIjoxNzYxMDY4NTI5LCJyb2xlcyI6IlVTRVIiLCJ1c2VybmFtZSI6Im1hcmlhbSJ9.ZDzovItUpBZn25yHM6XHWTAO0T5bPvzkYc6VcWJG8Kg

###

### delete medicineLog by id
GET http://localhost:7007/api/medicineTracker/medicineLog/1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJcIk1hcmlhbSBFbG1pclwiIiwic3ViIjoibWFyaWFtIiwiZXhwIjoxNzYxMDY4NTI5LCJyb2xlcyI6IlVTRVIiLCJ1c2VybmFtZSI6Im1hcmlhbSJ9.ZDzovItUpBZn25yHM6XHWTAO0T5bPvzkYc6VcWJG8Kg


###

### Update medicineLog by ID
PUT http://localhost:7007/api/medicineTracker/medicineLog/1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJcIk1hcmlhbSBFbG1pclwiIiwic3ViIjoibWFyaWFtIiwiZXhwIjoxNzYxMDY4NTI5LCJyb2xlcyI6IlVTRVIiLCJ1c2VybmFtZSI6Im1hcmlhbSJ9.ZDzovItUpBZn25yHM6XHWTAO0T5bPvzkYc6VcWJG8Kg


{
  "dose": 30.0,
  "takenAt": "2025-10-21T12:00:00"
}

###

# =========================
### User Tests

### Security
POST http://{{url}}/api/medicineTracker/auth/login
Content-Type: application/json

{
  "username": "mariam",
  "password": "1234"
}


###
GET http://{{url}}/api/medicineTracker/protected/user_demo
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJcIk1hcmlhbSBFbG1pclwiIiwic3ViIjoibWFyaWFtIiwiZXhwIjoxNzYxMDQ4OTU4LCJyb2xlcyI6IlVTRVIiLCJ1c2VybmFtZSI6Im1hcmlhbSJ9.hE6afPyxjHtAfxzhCCZyjZfrb5u-LQngz44nZIlbGKQ

### registere
POST http://{{url}}/api/medicineTracker/auth/register
Content-Type: application/json

{
  "username": "test",
  "password": "1234"
}

###

### logger ind med den registeret bruger
POST http://localhost:7007/api/medicineTracker/auth/login
Content-Type: application/json

{
  "username": "test",
  "password": "1234"
}


###

### tjekker om det valid
GET http://{{url}}/api/medicineTracker/protected/user_demo
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJcIk1hcmlhbSBFbG1pclwiIiwic3ViIjoidGVzdCIsImV4cCI6MTc2MTA0OTA1NSwicm9sZXMiOiJVc2VyIiwidXNlcm5hbWUiOiJ0ZXN0In0.ESMsOXv-vizV1sGY2oE-LEFwhhCHUKjQH5nCH5iVYWI


###